# Hubi -- Cloud Run production image.
#
# This image contains ONLY what Hubi needs to serve users: the built Next.js
# app and its traced production dependencies. It does not contain the Claude
# Code CLI, does not require `claude auth login`, and does not contain the
# Content Repository (~2GB) -- that lives in GCS, fetched at runtime by
# lib/ingestion/contentSource.ts. See docs/gcp-deployment-guide.md.
#
# Local development is unaffected by this file: `npm run dev` never touches
# Docker. This image exists solely for the Cloud Run deployment path.

# ---- deps: install once, cached across builds unless package*.json change ----
FROM node:22-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---- builder: compile the Next.js standalone output ----
FROM node:22-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# HUBI_REASONING_PROVIDER/GCS settings are runtime env vars, not build-time --
# nothing GCP-specific needs to be known at image-build time.
RUN npm run build

# ---- runner: minimal runtime image ----
FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

# Next.js "standalone" output (see next.config.mjs) already contains a
# pruned node_modules with only the packages actually used at runtime --
# do not `npm ci` again in this stage.
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
# Uncomment if/when a public/ directory is added to the app:
# COPY --from=builder /app/public ./public

# Cloud Run injects PORT at runtime (defaults to 8080) and expects the
# container to listen on it -- server.js (generated by the standalone
# build) already reads process.env.PORT. HOSTNAME must be 0.0.0.0, not
# 127.0.0.1 -- the local-only bind in package.json's "dev"/"start" scripts
# is a deliberate prototype-security choice (Architecture.md Section 17.1)
# that does not apply here: Cloud Run access control is handled at the
# platform level (IAM invoker permissions), not by binding to localhost.
ENV HOSTNAME=0.0.0.0
EXPOSE 8080

CMD ["node", "server.js"]
